// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("ru.org.openam.iis.httpmodule")]
[assembly: System.Reflection.AssemblyDescription("OpenAM Web Agent for IIS (.Net)")]
[assembly: System.Reflection.AssemblyCompany("3A Systems, LLC")]
[assembly: System.Reflection.AssemblyProduct("OpenAM")]
[assembly: System.Reflection.AssemblyCopyright("support@openam.org.ru")]
[assembly: System.Reflection.AssemblyVersion("1.0.2")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.2")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.2/master-43f6bce")]


